//! `ci init` — emit a GitHub Actions workflow that runs the TestSprite gate on
//! every pull request, so a red test blocks the merge. This is the local
//! analogue of TestSprite 2.1's "every PR auto-triggers the suite, failures
//! block merge" — the engine (`gate`: run + JUnit + `gh` PR comment + exit 1)
//! already exists; this just wires it into CI.

use std::path::{Path, PathBuf};

const WORKFLOW: &str = r#"name: TestSprite Gate
# Runs the stored TestSprite suite on every pull request and fails the check if
# any test fails, so a red test blocks the merge.
# Generated by `testsprite-rs ci init` — edit freely.
on:
  pull_request:
  workflow_dispatch:

jobs:
  testsprite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install testsprite-rs
        run: cargo install --git https://github.com/Miasin-Labs/testsprite-rs --locked
      - name: Run the TestSprite gate
        env:
          # Optional: only needed for LLM-backed (spec-less) tests. Deterministic
          # command/rust/spec tests run without it.
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: testsprite-rs gate
"#;

/// Write `.github/workflows/testsprite.yml` under `root`. Refuses to overwrite
/// an existing file unless `force`. Returns the path written.
pub fn init(root: &Path, force: bool) -> anyhow::Result<PathBuf> {
    let dir = root.join(".github").join("workflows");
    std::fs::create_dir_all(&dir)?;
    let path = dir.join("testsprite.yml");
    if path.exists() && !force {
        anyhow::bail!(
            "{} already exists (pass --force to overwrite)",
            path.display()
        );
    }
    std::fs::write(&path, WORKFLOW)?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn writes_workflow_then_refuses_overwrite_without_force() {
        let dir = std::env::temp_dir().join(format!("tsci-{}-{}", std::process::id(), "t"));
        let _ = std::fs::remove_dir_all(&dir);

        let p = init(&dir, false).unwrap();
        assert!(p.exists());
        let body = std::fs::read_to_string(&p).unwrap();
        assert!(body.contains("on:\n  pull_request:"));
        assert!(body.contains("testsprite-rs gate"));

        // second write without --force is refused
        assert!(init(&dir, false).is_err());
        // with --force it overwrites
        assert!(init(&dir, true).is_ok());

        std::fs::remove_dir_all(&dir).ok();
    }
}
